insert into Enrollment values (1, 'Advanced', 4, 'NT Church History / Life of Christ', 'T', 'Biblical Studies', 'Christian Studies', 1, 12, NULL)
insert into Enrollment values (2, 'Advanced', 4, 'Apologetics III', 'T', NULL, 'Christian Studies', 1, 6, NULL)
insert into Enrollment values (3, 'Advanced', 4, 'Algebra II', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (4, 'Advanced', 4, 'English III / English IV', 'T', 'English', 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (5, 'Advanced', 4, 'Chemistry / Physics', 'T', 'Chemistry', 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (6, 'Advanced', 4, 'History of Civilisation II', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (7, 'Advanced', 4, 'Further Credit Option', 'F', 'Further Credit Option', 'Miscellaneous', 8, 12, NULL)
insert into Enrollment values (8, 'Advanced', 4, 'Coursework 1', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (9, 'Advanced', 4, 'Coursework 2', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (10, 'Advanced', 4, 'Coursework 3', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (11, 'Advanced Maths Bias', 6, 'NT Church History / Life of Christ', 'T', 'Biblical Studies', 'Christian Studies', 1, 12, NULL)
insert into Enrollment values (12, 'Advanced Maths Bias', 6, 'Apologetics III', 'F', NULL, 'Christian Studies', 1, 6, NULL)
insert into Enrollment values (13, 'Advanced Maths Bias', 6, 'Algebra II', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (14, 'Advanced Maths Bias', 6, 'Trigonometry', 'F', NULL, 'Core Academic Studies', 2, 6, NULL)
insert into Enrollment values (15, 'Advanced Maths Bias', 6, 'Higher Maths', 'F', NULL, 'Core Academic Studies', 2, 6, NULL)
insert into Enrollment values (16, 'Advanced Maths Bias', 6, 'College Maths I', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (17, 'Advanced Maths Bias', 6, 'College Maths II', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (18, 'Advanced Maths Bias', 6, 'Physics', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (19, 'Advanced Maths Bias', 6, 'ICT Course', 'T', 'ICT Course', 'Core Expanded Studies', 3, 12, NULL)
insert into Enrollment values (20, 'Advanced Maths Bias', 6, 'Further Credit Option', 'T', 'Further Credit Option', 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (21, 'Advanced Maths Bias', 6, 'Coursework 1', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (22, 'Advanced Maths Bias', 6, 'Coursework 2', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (23, 'Advanced Maths Bias', 6, 'Coursework 3', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (24, 'Advanced Social Studies Bias', 7, 'NT Church History / Life of Christ', 'T', 'Biblical Studies', 'Christian Studies', 1, 12, NULL)
insert into Enrollment values (25, 'Advanced Social Studies Bias', 7, 'Apologetics III', 'F', NULL, 'Christian Studies', 1, 6, NULL)
insert into Enrollment values (26, 'Advanced Social Studies Bias', 7, 'English III', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (27, 'Advanced Social Studies Bias', 7, 'English Composition II', 'F', NULL, 'Core Academic Studies', 2, 12, 'Andere nummers in PACE')
insert into Enrollment values (28, 'Advanced Social Studies Bias', 7, 'History of Civilisation II', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (29, 'Advanced Social Studies Bias', 7, 'Economics and Civics', 'F', NULL, 'Core Academic Studies', 2, 12, 'Andere naam dan in FCO')
insert into Enrollment values (30, 'Advanced Social Studies Bias', 7, 'Further Credit Option', 'T', 'Further Credit Option', 'Miscellaneous', 8, 12, NULL)
insert into Enrollment values (31, 'Advanced Social Studies Bias', 7, 'Coursework 1', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (32, 'Advanced Social Studies Bias', 7, 'Coursework 2', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (33, 'Advanced Social Studies Bias', 7, 'Coursework 3', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (34, 'Advanced Science Bias', 8, 'NT Church History / Life of Christ', 'T', NULL, 'Christian Studies', 1, 12, NULL)
insert into Enrollment values (35, 'Advanced Science Bias', 8, 'Apologetics III', 'F', NULL, 'Christian Studies', 1, 6, NULL)
insert into Enrollment values (36, 'Advanced Science Bias', 8, 'Algebra II', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (37, 'Advanced Science Bias', 8, 'Trigonometry', 'F', NULL, 'Core Academic Studies', 2, 6, NULL)
insert into Enrollment values (38, 'Advanced Science Bias', 8, 'Higher Maths', 'F', NULL, 'Core Academic Studies', 2, 6, NULL)
insert into Enrollment values (39, 'Advanced Science Bias', 8, 'Chemistry', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (40, 'Advanced Science Bias', 8, 'Physics', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (41, 'Advanced Science Bias', 8, 'Biology (Apologia)', 'F', NULL, 'Core Academic Studies', 2, 12, NULL)
insert into Enrollment values (42, 'Advanced Science Bias', 8, 'Further Credit Option', 'F', NULL, 'Miscellaneous', 8, 12, NULL)
insert into Enrollment values (43, 'Advanced Science Bias', 8, 'Coursework 1', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (44, 'Advanced Science Bias', 8, 'Coursework 2', 'T', 'Coursework', 'Coursework', 7, 2, NULL)
insert into Enrollment values (45, 'Advanced Science Bias', 8, 'Coursework 3', 'T', 'Coursework', 'Coursework', 7, 2, NULL)

