insert into Course values (1, 'Maths Reading Readiness', 0, 1, 12, 12, 1, 'Maths', 'MA', NULL, 'RR', 2, 'Core Academic Studies', 'Core')
insert into Course values (2, 'Maths Level 1', 1, 1, 12, 12, 1, 'Maths', 'MA', NULL, 'MA', 2, 'Core Academic Studies', 'Core')
insert into Course values (3, 'English Level 1', 1, 1, 12, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (4, 'Word Building Level 1', 1, 1, 12, 12, 3, 'Word Building', 'WB', NULL, 'WB', 2, 'Core Academic Studies', 'Core')
insert into Course values (5, 'Literature and Creative Writing Level 1', 1, 1, 12, 12, 4, 'Literature', 'LI', NULL, 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (6, 'Science Level 1', 1, 1, 12, 12, 5, 'Science', 'SC', NULL, 'SC', 2, 'Core Academic Studies', 'Core')
insert into Course values (7, 'Social Studies Level 1', 1, 1, 12, 12, 6, 'Social Studies', 'SS', NULL, 'SS', 2, 'Core Academic Studies', 'Core')
insert into Course values (8, 'Bible Reading Level 1', 1, 1, 12, 12, 7, 'Biblical Studies', 'BS', NULL, 'BR', 1, 'Christian Studies', 'Core')
insert into Course values (9, 'Maths Level 2', 2, 13, 24, 12, 1, 'Maths', 'MA', NULL, 'MA', 2, 'Core Academic Studies', 'Core')
insert into Course values (10, 'English Level 2', 2, 13, 24, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (11, 'Word Building Level 2', 2, 13, 24, 12, 3, 'Word Building', 'WB', NULL, 'WB', 2, 'Core Academic Studies', 'Core')
insert into Course values (12, 'Literature and Creative Writing Level 2', 2, 13, 24, 12, 4, 'Literature', 'LI', NULL, 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (13, 'Science Level 2', 2, 13, 24, 12, 5, 'Science', 'SC', NULL, 'SC', 2, 'Core Academic Studies', 'Core')
insert into Course values (14, 'Social Studies Level 2', 2, 13, 24, 12, 6, 'Social Studies', 'SS', NULL, 'SS', 2, 'Core Academic Studies', 'Core')
insert into Course values (15, 'Bible Reading Level 2', 2, 13, 24, 12, 7, 'Biblical Studies', 'BS', NULL, 'BR', 1, 'Christian Studies', 'Core')
insert into Course values (16, 'Maths Level 3', 3, 25, 36, 12, 1, 'Maths', 'MA', NULL, 'MA', 2, 'Core Academic Studies', 'Core')
insert into Course values (17, 'English Level 3', 3, 25, 36, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (18, 'Word Building Level 3', 3, 25, 36, 12, 3, 'Word Building', 'WB', NULL, 'WB', 2, 'Core Academic Studies', 'Core')
insert into Course values (19, 'Literature and Creative Writing Level 3', 3, 25, 36, 12, 4, 'Literature', 'LI', NULL, 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (20, 'Science Level 3', 3, 25, 36, 12, 5, 'Science', 'SC', NULL, 'SC', 2, 'Core Academic Studies', 'Core')
insert into Course values (21, 'Social Studies Level 3', 3, 25, 36, 12, 6, 'Social Studies', 'SS', NULL, 'SS', 2, 'Core Academic Studies', 'Core')
insert into Course values (22, 'Bible Reading Level 3', 3, 25, 36, 12, 7, 'Biblical Studies', 'BS', NULL, 'BR', 1, 'Christian Studies', 'Core')
insert into Course values (23, 'Maths Level 4', 4, 37, 48, 12, 1, 'Maths', 'MA', NULL, 'MA', 2, 'Core Academic Studies', 'Core')
insert into Course values (24, 'English Level 4', 4, 37, 48, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (25, 'Word Building Level 4', 4, 37, 48, 12, 3, 'Word Building', 'WB', NULL, 'WB', 2, 'Core Academic Studies', 'Core')
insert into Course values (26, 'Literature and Creative Writing Level 4', 4, 37, 48, 12, 4, 'Literature', 'LI', NULL, 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (27, 'Science Level 4', 4, 37, 48, 12, 5, 'Science', 'SC', NULL, 'SC', 2, 'Core Academic Studies', 'Core')
insert into Course values (28, 'Social Studies Level 4', 4, 37, 48, 12, 6, 'Social Studies', 'SS', NULL, 'SS', 2, 'Core Academic Studies', 'Core')
insert into Course values (29, 'Bible Reading Level 4', 4, 37, 48, 12, 7, 'Biblical Studies', 'BS', NULL, 'BR', 1, 'Christian Studies', 'Core')
insert into Course values (30, 'Maths Level 5', 5, 49, 60, 12, 1, 'Maths', 'MA', NULL, 'MA', 2, 'Core Academic Studies', 'Core')
insert into Course values (31, 'English Level 5', 5, 49, 60, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (32, 'Word Building Level 5', 5, 49, 60, 12, 3, 'Word Building', 'WB', NULL, 'WB', 2, 'Core Academic Studies', 'Core')
insert into Course values (33, 'Literature and Creative Writing Level 5', 5, 49, 60, 12, 4, 'Literature', 'LI', NULL, 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (34, 'Science Level 5', 5, 49, 60, 12, 5, 'Science', 'SC', NULL, 'SC', 2, 'Core Academic Studies', 'Core')
insert into Course values (35, 'Social Studies Level 5', 5, 49, 60, 12, 6, 'Social Studies', 'SS', NULL, 'SS', 2, 'Core Academic Studies', 'Core')
insert into Course values (36, 'Bible Reading Level 5', 5, 49, 60, 12, 7, 'Biblical Studies', 'BS', NULL, 'BR', 1, 'Christian Studies', 'Core')
insert into Course values (37, 'Maths Level 6', 6, 61, 72, 12, 1, 'Maths', 'MA', NULL, 'MA', 2, 'Core Academic Studies', 'Core')
insert into Course values (38, 'English Level 6', 6, 61, 72, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (39, 'Word Building Level 6', 6, 61, 72, 12, 3, 'Word Building', 'WB', NULL, 'WB', 2, 'Core Academic Studies', 'Core')
insert into Course values (40, 'Literature and Creative Writing Level 6', 6, 61, 72, 12, 4, 'Literature', 'LI', NULL, 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (41, 'Science Level 6', 6, 61, 72, 12, 5, 'Science', 'SC', NULL, 'SC', 2, 'Core Academic Studies', 'Core')
insert into Course values (42, 'Social Studies Level 6', 6, 61, 72, 12, 6, 'Social Studies', 'SS', NULL, 'SS', 2, 'Core Academic Studies', 'Core')
insert into Course values (43, 'Bible Reading Level 6', 6, 61, 72, 12, 7, 'Biblical Studies', 'BS', NULL, 'BR', 1, 'Christian Studies', 'Core')
insert into Course values (44, 'Maths Level 7', 7, 73, 84, 12, 1, 'Maths', 'MA', NULL, 'MA', 2, 'Core Academic Studies', 'Core')
insert into Course values (45, 'English Level 7', 7, 73, 84, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (46, 'Beginning Art', 7, 73, 84, 12, 3, 'Word Building', 'WB', NULL, 'BA', 2, 'Core Academic Studies', 'Core')
insert into Course values (47, 'Word Building Level 7', 7, 73, 84, 12, 3, 'Word Building', 'WB', NULL, 'WB', 2, 'Core Academic Studies', 'Core')
insert into Course values (48, 'Literature Level 7', 7, 74, 84, NULL, 4, 'Literature', 'LI', 'Alleen even getallen hebben PACE beschikbaar', 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (49, 'Science Level 7', 7, 73, 84, 12, 5, 'Science', 'SC', NULL, 'SC', 2, 'Core Academic Studies', 'Core')
insert into Course values (50, 'Social Studies Level 7', 7, 73, 78, NULL, 6, 'Social Studies', 'SS', NULL, 'SS', 2, 'Core Academic Studies', 'Core')
insert into Course values (51, 'Staatsinrichting', 7, 1, 3, 3, 6, 'Social Studies', 'SS', NULL, 'SI', 2, 'Core Academic Studies', 'Core')
insert into Course values (52, '?', 7, 73, 84, 12, 7, 'Biblical Studies', 'BS', 'Geen BS dit jaar?', '?', 2, 'Core Academic Studies', 'Core')
insert into Course values (53, 'General Maths', 8, 85, 96, 12, 1, 'Maths', 'MA', NULL, 'GM', 2, 'Core Academic Studies', 'Core')
insert into Course values (54, 'General English', 8, 85, 96, 12, 2, 'Language', 'LA', NULL, 'EN', 1, 'Christian Studies', 'Core')
insert into Course values (55, 'Word Building Level 8', 8, 85, 96, 12, 3, 'Word Building', 'WB', NULL, 'WB', 1, 'Christian Studies', 'Core')
insert into Course values (56, 'Literature Level 8', 8, 86, 96, NULL, 4, 'Literature', 'LI', 'Alleen even getallen hebben PACE beschikbaar', 'LC', 1, 'Christian Studies', 'Core')
insert into Course values (57, 'Earth Science Level 8', 8, 85, 96, 12, 5, 'Science', 'SC', NULL, 'ES', 2, 'Core Academic Studies', 'Core')
insert into Course values (58, 'British and European History', 8, 85, 96, 12, 6, 'Social Studies', 'SS', NULL, 'UK', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (59, 'World History', 8, 85, 96, 12, 6, 'Social Studies', 'SS', NULL, 'WH', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (60, 'New Testament Survey', 8, 97, 102, NULL, 7, 'Biblical Studies', 'BS', NULL, 'NT', 1, 'Christian Studies', 'Core')
insert into Course values (61, 'Algebra I', 9, 97, 108, 12, 1, 'Maths', 'MA', NULL, 'AL', 1, 'Christian Studies', 'Core')
insert into Course values (62, 'English I', 9, 97, 108, 12, 2, 'Language', 'LA', NULL, 'EN', 1, 'Christian Studies', 'Core')
insert into Course values (63, 'French I', 9, 97, 108, 12, 2, 'Language', 'LA', NULL, 'FR', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (64, 'Rosetta Stone Level 9', 9, 1, 2, NULL, 2, 'Language', 'LA', 'Extended Levels only', 'RS', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (65, 'Spanish I', 9, 1, 12, 12, 2, 'Language', 'LA', NULL, 'ES', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (66, 'Advanced Art', 9, 97, 108, 12, 10, 'Supplementary', 'SU', NULL, 'AA', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (67, 'Complete Art', 9, 1, 10, NULL, 10, 'Supplementary', 'SU', NULL, 'CA', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (68, 'Etymology', 9, 97, 108, 12, 3, 'Word Building', 'WB', NULL, 'ET', 1, 'Christian Studies', 'Core')
insert into Course values (69, 'Music', 9, 1, 6, NULL, 10, 'Supplementary', 'SU', NULL, 'MU', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (70, 'Music Theory/Performance Grade 5', 9, 5, 6, 12, 10, 'Supplementary', 'SU', NULL, 'MT', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (71, 'Music Theory/Performance', 9, 5, 6, 12, 10, 'Supplementary', 'SU', 'Is duplicate of 70? Or perhaps the other one is theory and this one is performance', 'MT', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (72, 'Speech', 9, 1, 6, NULL, 3, 'Word Building', 'WB', NULL, 'SP', 3, 'Core Expanded Studies', 'Core')
insert into Course values (73, 'ICCE Literature Level 9', 9, 1, 4, 6, 4, 'Literature', 'LI', NULL, 'I9', 2, 'Core Academic Studies', 'Core')
insert into Course values (146, 'Literature Level 9', 9, 98, 108, NULL, 4, 'Literature', 'LI', 'Alleen even getallen hebben PACE beschikbaar', 'LC', 2, 'Core Academic Studies', 'Core')
insert into Course values (74, 'Astronomy', 9, 1, 5, NULL, 5, 'Science', 'SC', NULL, 'AS', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (75, 'Biology Level 9', 9, 97, 108, 12, 5, 'Science', 'SC', NULL, 'BI', 2, 'Core Academic Studies', 'Core')
insert into Course values (76, 'Health', 9, 1, 6, NULL, 5, 'Science', 'SC', NULL, 'HE', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (77, 'Nutrition Science', 9, 1, 6, NULL, 5, 'Science', 'SC', NULL, 'NS', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (78, 'Sport + Health', 9, 1, 4, 12, 5, 'Science', 'SC', 'Is een combinatie vak dat alleen met Health samen gedaan kan worden? ON HOLD Informatie moet nog bevestigd worden', 'SP', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (79, 'A.C.E. Training', 9, NULL, NULL, 6, 10, 'Supplementary', 'SU', NULL, 'AC', 4, 'Applied Studies', 'Further Credit Option')
insert into Course values (80, 'World Geography', 9, 97, 108, 12, 6, 'Social Studies', 'SS', NULL, 'WG', 2, 'Core Academic Studies', 'Core')
insert into Course values (81, 'Apologetics I', 9, 1, 2, 6, 7, 'Biblical Studies', 'BS', NULL, 'AP', 1, 'Christian Studies', 'Core')
insert into Course values (82, 'Missions', 9, 1, 6, 6, 7, 'Biblical Studies', 'BS', NULL, 'MI', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (83, 'Successful Living', 9, 1, 12, 12, 7, 'Biblical Studies', 'BS', NULL, 'SL', 1, 'Christian Studies', 'Core')
insert into Course values (84, 'A.C.E. Training + 30 hours of service', 9, NULL, NULL, 12, 10, 'Supplementary', 'SU', NULL, 'AT', 4, 'Applied Studies', 'Further Credit Option')
insert into Course values (85, 'ECDL Course', 9, 1, 8, NULL, 10, 'Supplementary', 'SU', 'Wat is dit? ', 'ED', 3, 'Core Expanded Studies', 'Core')
insert into Course values (86, 'Geometry', 10, 109, 120, 12, 1, 'Maths', 'MA', NULL, 'GE', 2, 'Core Academic Studies', 'Core')
insert into Course values (87, 'English II', 10, 109, 120, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (88, 'Rosetta Stone Level 10', 10, 3, 5, 6, 2, 'Language', 'LA', 'Each six stars', 'RS', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (89, 'Music Theory/Performance Grade 6', 10, NULL, NULL, 12, 10, 'Supplementary', 'SU', NULL, 'MT', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (90, 'Physical Science', 10, 109, 120, 12, 5, 'Science', 'SC', 'Dat klopt', 'PS', 2, 'Core Academic Studies', 'Core')
insert into Course values (91, 'History of Civilisation I', 10, 1, 10, NULL, 6, 'Social Studies', 'SS', NULL, 'HC', 2, 'Core Academic Studies', 'Core')
insert into Course values (92, 'Apologetics II', 10, 3, 4, 6, 7, 'Biblical Studies', 'BS', 'Hier mag gekozen worden voor Apologetics II (i.e. boekjes 3 en 4) of uit Groep 1 (i.e. Christian Studies, van Intermediate)', 'AP', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (93, 'Christian Counselling I', 10, 1, 5, NULL, 7, 'Biblical Studies', 'BS', 'Correct gespeld? Is Amerikaans materiaal maar Britse spelling?', 'CC', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (94, 'Life of Christ I', 10, 133, 138, NULL, 7, 'Biblical Studies', 'BS', NULL, 'LC', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (95, 'Old Testament Survey', 10, 109, 120, 12, 7, 'Biblical Studies', 'BS', NULL, 'OT', 1, 'Christian Studies', 'Core')
insert into Course values (96, 'Auto Mechanics', 10, 109, 114, NULL, 10, 'Supplementary', 'SU', NULL, 'AM', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (97, 'ICT Course', 10, NULL, NULL, 12, 10, 'Supplementary', 'SU', 'From approved list', 'IC', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (98, 'Algebra II', 11, 121, 132, 12, 1, 'Maths', 'MA', NULL, 'AL', 2, 'Core Academic Studies', 'Core')
insert into Course values (99, 'British Literature', 11, 1, 5, NULL, 2, 'Language', 'LA', NULL, 'BL', 2, 'Core Academic Studies', 'Core')
insert into Course values (100, 'Dutch Language Staatsexamen HAVO', 11, NULL, NULL, 18, 2, 'Language', 'LA', 'Staatsexamen Havo, where is VWO?', 'NL', 2, 'Core Academic Studies', 'Core')
insert into Course values (101, 'English III', 11, 121, 132, 12, 2, 'Language', 'LA', NULL, 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (102, 'ICCE Literature 10 Part 1', 11, 1, 3, 6, 4, 'Literature', 'LI', 'Beide vakken hebben dezelfde naam. Specification is niet duidelijk, is moeilijk met twee karakters. Beter is "I10" vs "I09". ', 'I1', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (103, 'ICCE Literature 10 Part 2', 11, 1, 6, NULL, 4, 'Literature', 'LI', 'Overlap with the previous one and the same name', 'I1', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (104, 'N.T. Greek I', 11, 121, 132, 12, 2, 'Language', 'LA', NULL, 'GR', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (105, 'Chemistry', 11, 121, 132, 12, 5, 'Science', 'SC', NULL, 'CH', 2, 'Core Academic Studies', 'Core')
insert into Course values (106, 'New Testament Church History', 12, 121, 132, 12, 7, 'Biblical Studies', 'BS', 'Heeft overlap met NT Ch. Hist. II?', 'NC', 1, 'Christian Studies', 'Core')
insert into Course values (107, 'Accounting (US)', 12, 121, 132, 12, 1, 'Maths', 'MA', NULL, 'AC', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (108, 'College Maths I', 12, 1, 10, NULL, 1, 'Maths', 'MA', NULL, 'CM', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (109, 'College Maths II', 12, 11, 20, NULL, 1, 'Maths', 'MA', NULL, 'CM', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (110, 'Higher Maths', 12, 139, 144, NULL, 1, 'Maths', 'MA', NULL, 'HM', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (111, 'Trigonometry', 12, 133, 138, NULL, 1, 'Maths', 'MA', NULL, 'TR', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (112, 'English Composition II', 12, 1, 10, NULL, 2, 'Language', 'LA', 'Where is English Composition I?', 'EC', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (113, 'English IV', 12, 133, 144, 12, 2, 'Language', 'LA', 'mogelijk English IV te kiezen als III nog niet gedaan is? ', 'EN', 2, 'Core Academic Studies', 'Core')
insert into Course values (114, 'N.T. Greek II', 12, 11, 20, NULL, 2, 'Language', 'LA', 'Nieuwe nummering?', 'GR', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (115, 'Music Theory/Performance Grade 7/8', 12, 7, 8, NULL, 10, 'Supplementary', 'SU', NULL, 'MT', 3, 'Core Expanded Studies', 'Further Credit Option')
insert into Course values (116, 'College Physical Science', 12, 1, 10, NULL, 5, 'Science', 'SC', NULL, 'CP', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (117, 'Physics', 12, 133, 144, 12, 5, 'Science', 'SC', NULL, 'PH', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (118, 'American History', 12, 85, 96, 12, 6, 'Social Studies', 'SS', 'Credit Option', 'AH', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (119, 'Civics and Economics', 12, 133, 144, 12, 6, 'Social Studies', 'SS', NULL, 'CE', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (120, 'Collectivism', 12, 133, 138, NULL, 6, 'Social Studies', 'SS', 'Over communisme en zo', 'CO', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (121, 'History of Civilisation II', 12, 11, 20, NULL, 6, 'Social Studies', 'SS', 'Dit staat ook onder FCO, maar is verplicht!?', 'HC', 2, 'Core Academic Studies', 'Core')
insert into Course values (122, 'US Constitution', 12, 133, 136, 6, 6, 'Social Studies', 'SS', NULL, 'UC', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (123, 'Christian Counselling II', 12, 6, 10, NULL, 7, 'Biblical Studies', 'BS', 'Apologetics option only?', 'CC', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (124, 'Christian Growth I', 12, 133, 138, NULL, 7, 'Biblical Studies', 'BS', NULL, 'CG', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (125, 'Life of Christ II', 12, 139, 144, NULL, 7, 'Biblical Studies', 'BS', 'Only possible to choose this as an option for Apologetics III', 'LC', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (126, 'New Testament Church History II', 12, 127, 132, NULL, 7, 'Biblical Studies', 'BS', 'Apologetics option only? ', 'NC', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (127, 'English Composition I', 10, 1, 10, NULL, 2, 'Language', 'LA', 'Welk level? Staat niet op het blad', 'EC', 2, 'Core Academic Studies', 'Core')
insert into Course values (128, 'Apologetics III', 12, NULL, NULL, 12, 7, 'Biblical Studies', 'BS', 'Hier mag gekozen worden uit Groep 1 (i.e. Christian Studies, van Advanced). Deze regel moet verwijderd worden, is namelijk geen aparte course.', 'AP', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (129, 'ICCE Biology', 9, 1, 6, NULL, 5, 'Science', 'SC', NULL, 'IB', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (130, 'Biology Apologia', 10, 1, 16, NULL, 5, 'Science', 'SC', NULL, 'BA', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (131, 'Life of Christ', 12, 133, 144, 12, 7, 'Biblical Studies', 'BS', NULL, 'LC', 1, 'Christian Studies', 'Further Credit Option')
insert into Course values (132, 'Dutch Language Staatsexamen VMBO', 9, NULL, NULL, 12, 2, 'Language', 'LA', NULL, 'NL', 2, 'Core Academic Studies', 'Further Credit Option')
insert into Course values (133, 'Social Studies Essay General', 9, NULL, NULL, 3, 6, 'Social Studies', 'SS', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (134, 'Science Essay General', 9, NULL, NULL, 3, 5, 'Science', 'SC', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (135, 'Biblical Studies Essay Intermediate', 10, NULL, NULL, 2, 7, 'Biblical Studies', 'BS', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (136, 'English Essay Intermediate', 10, NULL, NULL, 2, 2, 'Language', 'LA', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (137, 'Social Studies Essay Intermediate', 10, NULL, NULL, 2, 6, 'Social Studies', 'SS', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (138, 'Science Essay Intermediate', 10, NULL, NULL, 2, 5, 'Science', 'SC', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (139, 'Biblical Studies Essay Advanced', 12, NULL, NULL, 2, 7, 'Biblical Studies', 'BS', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (140, 'Maths Paper Advanced', 12, NULL, NULL, 2, 1, 'Maths', 'MA', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (141, 'English Essay Advanced', 12, NULL, NULL, 2, 2, 'Language', 'LA', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (142, 'Social Studies Essay Advanced', 12, NULL, NULL, 2, 6, 'Social Studies', 'SS', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (143, 'Sciences Project Advanced', 12, NULL, NULL, 2, 5, 'Science', 'SC', NULL, 'PR', 7, 'Coursework', 'CourseWork')
insert into Course values (144, 'Sciences Essay Advanced', 12, NULL, NULL, 2, 5, 'Science', 'SC', NULL, 'ES', 7, 'Coursework', 'CourseWork')
insert into Course values (145, 'English III Dissertation', 12, NULL, NULL, 2, 2, 'Language', 'LA', NULL, 'DS', 7, 'Coursework', 'CourseWork')

