insert into Transaction values (1, NULL, NULL, 'Registration', NULL)
insert into Transaction values (2, NULL, NULL, 'Left school without graduation', NULL)
insert into Transaction values (3, NULL, NULL, 'graduation General Certificate', NULL)
insert into Transaction values (4, NULL, NULL, NULL, NULL)
insert into Transaction values (5, NULL, NULL, NULL, NULL)
insert into Transaction values (6, NULL, NULL, NULL, NULL)
insert into Transaction values (7, NULL, NULL, NULL, NULL)
insert into Transaction values (8, NULL, NULL, NULL, NULL)
insert into Transaction values (9, NULL, NULL, NULL, NULL)
insert into Transaction values (10, NULL, NULL, NULL, NULL)
insert into Transaction values (11, NULL, NULL, NULL, NULL)
insert into Transaction values (12, NULL, NULL, NULL, NULL)
insert into Transaction values (13, NULL, NULL, NULL, NULL)
insert into Transaction values (14, NULL, NULL, NULL, NULL)

