insert into ICCE_Certificate values (1, 'Adeleke', NULL, 'Deborah', 'Deborah', NULL, cast('2007-01-01' as Date), 10, 'Student', 4, 2, 1, 1, 1)
insert into ICCE_Certificate values (2, 'Adeleke', NULL, 'Oluwatobi Samuel', 'Oluwatobi', NULL, cast('2005-08-21' as Date), 13, 'Student', 4, 2, 1, 1, 1)
insert into ICCE_Certificate values (3, 'Adeleke', NULL, 'Dorcas Mayowa Oluwatofarati Temitope Esther', 'Dorcas', NULL, cast('2007-06-15' as Date), 3, 'Student', 4, 2, 1, 1, 1)
insert into ICCE_Certificate values (4, 'Benschop', NULL, 'Jannetje Hendrika', 'Hannah', NULL, cast('2005-05-08' as Date), 1, 'Student', 4, 1, 2, 4, 1)
insert into ICCE_Certificate values (5, 'Boulahdaraj', NULL, 'Zakariya', 'Zakariya', NULL, cast('2004-04-19' as Date), 22, 'Student', 4, 1, 5, 1, 1)
insert into ICCE_Certificate values (6, 'Brand', 'van den', 'Ezra', 'Ezra', NULL, cast('2001-05-20' as Date), 10, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (7, 'Brand', 'van den', 'Lois-Daan', 'Lois-Daan', NULL, cast('2003-03-26' as Date), 17, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (8, 'Bruijne', 'de', 'Matthias', 'Matthias', NULL, cast('2004-09-28' as Date), 13, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (9, 'Choi', NULL, 'Byeol', 'Byeol', NULL, cast('2005-03-06' as Date), 20, 'Student', 4, 1, 2, 2, 1)
insert into ICCE_Certificate values (10, 'Gonzalez Rodriguez', NULL, 'Eleazar Leonardo', 'Eleazar', NULL, cast('2004-07-09' as Date), 21, 'Student', 4, 1, 3, 1, 1)
insert into ICCE_Certificate values (11, 'Gunnink', NULL, 'Johannes David Bernardus', 'Daan', NULL, cast('2007-04-04' as Date), 12, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (12, 'Harkes', NULL, 'Marinus Dirk Martijn', 'Stijn', NULL, cast('2009-12-16' as Date), 19, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (13, 'Harkes', NULL, 'Jonathan Anne Theodoor', 'Jona', NULL, cast('2007-04-13' as Date), 7, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (14, 'Houweling', 'van', 'Benjamin Ezra', 'Ben', NULL, cast('2006-07-26' as Date), 8, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (15, 'Houweling', 'van', 'Noah Christian', 'Noah', NULL, cast('2007-06-30' as Date), 14, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (16, 'Houweling', 'van', 'Emma Rhodé', 'Aimée', NULL, cast('2006-12-11' as Date), 19, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (17, 'Kleef', 'van', 'Loïs Eunice', 'Loïs', NULL, cast('2009-03-24' as Date), 4, 'Student', 4, 1, 2, 3, 1)
insert into ICCE_Certificate values (18, 'Kleef', 'van', 'Jonathan', 'Jonathan', NULL, cast('2010-11-17' as Date), 8, 'Student', 4, 1, 2, 3, 1)
insert into ICCE_Certificate values (19, 'Lee ', NULL, 'Kang Kevin', 'Kevin', NULL, cast('2012-07-03' as Date), 23, 'Student', 4, 1, 6, 1, 1)
insert into ICCE_Certificate values (20, 'Lee ', NULL, 'Myung', 'Matthew', NULL, cast('2011-02-27' as Date), 15, 'Student', 4, 1, 6, 1, 1)
insert into ICCE_Certificate values (21, 'Littel', NULL, 'Beline Elizabeth', 'Lina', NULL, cast('2009-05-11' as Date), 11, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (22, 'Littel', NULL, 'Simon Johannes', 'Sam', NULL, cast('2008-07-09' as Date), 14, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (23, 'Littel', NULL, 'Catharina Johanna', 'Noa', NULL, cast('2008-05-10' as Date), 13, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (24, 'Trimp', NULL, 'Elbert Daniël', 'Dani', NULL, cast('2006-09-06' as Date), 19, 'Student', 4, 1, 3, 1, 1)
insert into ICCE_Certificate values (25, 'Trimp', NULL, 'Aron Pieter', 'Aron', NULL, cast('2004-07-27' as Date), 11, 'Student', 4, 1, 3, 1, 1)
insert into ICCE_Certificate values (26, 'Verwoerd', NULL, 'Cornelia Elisabeth', 'Isolde', NULL, cast('2002-09-09' as Date), 20, 'Student', 4, 1, 2, 4, 1)
insert into ICCE_Certificate values (27, 'Verwoerd', NULL, 'Martinus Gerardus', 'Magnus', NULL, cast('2004-10-01' as Date), 14, 'Student', 4, 1, 2, 4, 1)
insert into ICCE_Certificate values (28, 'Visser', NULL, 'Loïs', 'Loïs', NULL, cast('2002-05-24' as Date), 9, 'Student', 4, 1, 2, 1, 1)
insert into ICCE_Certificate values (29, 'Yong', NULL, 'Joseph Nathan Andrew Jun-Yin', 'Nathan', NULL, cast('2010-10-02' as Date), 17, 'Student', 4, 1, 4, 1, 1)
insert into ICCE_Certificate values (30, 'Yong', NULL, 'Andrew', 'Andrew', 'yartow@gmail.com', cast('2010-04-20' as Date), 17, 'Monitor', 0, 1, 2, 0, 1)
insert into ICCE_Certificate values (31, 'Bezemer', NULL, 'Simon', 'Simon', NULL, cast('2010-10-11' as Date), 13, 'Supervisor', 0, 1, 2, 0, 1)
insert into ICCE_Certificate values (32, 'Visser', NULL, 'Hannah', 'Hannah', NULL, cast('2011-08-28' as Date), 2, 'Supervisor', 0, 1, 2, 0, 1)
insert into ICCE_Certificate values (33, 'Trimp', NULL, 'Annelies', 'Annelies', NULL, cast('2012-02-18' as Date), 19, 'Supervisor', 0, 1, 2, 0, 1)
insert into ICCE_Certificate values (34, 'Westerhof', NULL, 'Petra', 'Petra', NULL, cast('2009-06-06' as Date), 23, 'Monitor', 0, 1, 2, 0, 1)
insert into ICCE_Certificate values (35, 'Kleef', 'van', 'Johanna', 'Johanna', NULL, cast('2007-04-03' as Date), 17, 'Supervisor', 0, 1, 2, 0, 1)
insert into ICCE_Certificate values (36, 'Bruin', 'de', 'Ada', 'Ada', NULL, cast('2004-07-26' as Date), 15, 'Supervisor', 0, 1, 2, 0, 1)
insert into ICCE_Certificate values (37, 'Lee ', NULL, 'Irene', 'Irene', 'irene7416@naver.com', cast('2004-05-24' as Date), 14, 'Monitor', 0, 6, 2, 0, 1)
insert into ICCE_Certificate values (38, 'Steenbeek', NULL, NULL, 'Lukas', NULL, NULL, NULL, 'Student', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (39, 'Steenbeek', NULL, NULL, 'Nathanaël', NULL, NULL, NULL, 'Student', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (40, 'Steenbeek', NULL, 'Felicia (?)', 'Anna', NULL, NULL, NULL, 'Student', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (41, 'Brand', 'van den', 'Joost', 'Joost', 'joostvandenbrand@gmail.com', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (42, 'Harkes', NULL, 'F.J. ', 'Frannie', 'harkesfj@gmail.com', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (43, 'Harkes', NULL, NULL, 'Dennis', NULL, NULL, NULL, 'Parent', NULL, NULL, NULL, NULL, NULL)
insert into ICCE_Certificate values (44, 'Houwenling', 'van', 'Rob', 'Rob', 'rob@vhouwenling.nl', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (45, 'Littel', NULL, 'Annemieke', 'Annemieke', 'aplittel@hotmail.com', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (46, 'Littel', NULL, 'Paul', 'Paul', 'aplittel@hotmail.com', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (47, 'Trimp', NULL, 'Hugo', 'Hugo', 'hugo@trimp.nl', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (48, 'Steenbeek', NULL, 'Robert', 'Robert', 'robertsteenbeek@hotmail.com', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (49, 'Wijngaarden', 'van', 'Jan', 'Jan', 'janvanwijngaarden@live.nl', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (50, 'Trimp', NULL, 'Claudia', 'Claudia', 'claudia@trimp.nl', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (51, 'seai81@hotmail.com', NULL, NULL, NULL, 'seai81@hotmail.com', NULL, NULL, 'Parent', NULL, NULL, 2, 0, 1)
insert into ICCE_Certificate values (52, 'Hoogendoorn', NULL, 'Claudia', 'Claudia', NULL, NULL, NULL, 'Parent', NULL, NULL, NULL, NULL, NULL)
insert into ICCE_Certificate values (53, 'Hoogendoorn', NULL, 'Boaz', 'Boaz', NULL, NULL, NULL, 'Student', NULL, NULL, NULL, NULL, NULL)

