insert into Subject values (1, 'Maths', 'Yellow', 'Academic', 'MA')
insert into Subject values (2, 'Language', 'Red', 'Academic', 'LA')
insert into Subject values (3, 'Word Building', 'Purple', 'Academic', 'WB')
insert into Subject values (4, 'Literature', 'DarkRed', 'Academic', 'LI')
insert into Subject values (5, 'Science', 'Blue', 'Academic', 'SC')
insert into Subject values (6, 'Social Studies', 'Green', 'Academic', 'SS')
insert into Subject values (7, 'Biblical Studies', 'SandOrange', 'Christian', 'BS')
insert into Subject values (8, 'Electives', 'Grey', 'Elective', 'EL')
insert into Subject values (9, 'Dutch Language', 'Orange', 'Academic', 'NL')
insert into Subject values (10, 'Supplementary', 'White', 'Elective', 'SU')
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)
insert into Subject values (NULL, NULL, NULL, NULL, NULL)

