insert into CourseWorkICCE_Certificate values (1, 2, 'General', 133, 'Social Studies Essay General')
insert into CourseWorkICCE_Certificate values (2, 2, 'General', 134, 'Science Essay General')
insert into CourseWorkICCE_Certificate values (3, 3, 'Intermediate', 135, 'Biblical Studies Essay Intermediate')
insert into CourseWorkICCE_Certificate values (4, 3, 'Intermediate', 136, 'English Essay Intermediate')
insert into CourseWorkICCE_Certificate values (5, 3, 'Intermediate', 137, 'Social Studies Essay Intermediate')
insert into CourseWorkICCE_Certificate values (6, 3, 'Intermediate', 138, 'Science Essay Intermediate')
insert into CourseWorkICCE_Certificate values (7, 4, 'Advanced', 139, 'Biblical Studies Essay Advanced')
insert into CourseWorkICCE_Certificate values (8, 4, 'Advanced', 140, 'Maths Paper Advanced')
insert into CourseWorkICCE_Certificate values (9, 4, 'Advanced', 141, 'English Essay Advanced')
insert into CourseWorkICCE_Certificate values (10, 4, 'Advanced', 142, 'Social Studies Essay Advanced')
insert into CourseWorkICCE_Certificate values (11, 4, 'Advanced', 143, 'Sciences Project Advanced')
insert into CourseWorkICCE_Certificate values (12, 4, 'Advanced', 144, 'Sciences Essay Advanced')
insert into CourseWorkICCE_Certificate values (13, 4, 'Advanced', 145, 'English III Dissertation')
insert into CourseWorkICCE_Certificate values (14, 6, 'Advanced Maths Bias', 139, 'Biblical Studies Essay Advanced')
insert into CourseWorkICCE_Certificate values (15, 6, 'Advanced Maths Bias', 140, 'Maths Paper Advanced')
insert into CourseWorkICCE_Certificate values (16, 6, 'Advanced Maths Bias', 143, 'Sciences Project Advanced')
insert into CourseWorkICCE_Certificate values (17, 6, 'Advanced Maths Bias', 144, 'Sciences Essay Advanced')
insert into CourseWorkICCE_Certificate values (18, 7, 'Advanced Social Studies Bias', 139, 'Biblical Studies Essay Advanced')
insert into CourseWorkICCE_Certificate values (19, 7, 'Advanced Social Studies Bias', 141, 'English Essay Advanced')
insert into CourseWorkICCE_Certificate values (20, 7, 'Advanced Social Studies Bias', 142, 'Social Studies Essay Advanced')
insert into CourseWorkICCE_Certificate values (21, 7, 'Advanced Social Studies Bias', 145, 'English III Dissertation')
insert into CourseWorkICCE_Certificate values (22, 8, 'Advanced Science Bias', 139, 'Biblical Studies Essay Advanced')
insert into CourseWorkICCE_Certificate values (23, 8, 'Advanced Science Bias', 140, 'Maths Paper Advanced')
insert into CourseWorkICCE_Certificate values (24, 8, 'Advanced Science Bias', 143, 'Sciences Project Advanced')
insert into CourseWorkICCE_Certificate values (25, 8, 'Advanced Science Bias', 144, 'Sciences Essay Advanced')

